---
name: Bug Report
description: Report a bug or unexpected behavior
title: '[BUG] '
labels: ['bug']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below
        to help us understand and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: List the steps to reproduce the bug
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected...
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment
      placeholder: |
        - **OS**: [e.g., Ubuntu 22.04, macOS 14.0]
        - **Container Runtime**: [e.g., Podman 4.0, Docker 24.0]
        - **Image Version/Tag**: [e.g., latest, dev, 1.0]
        - **Architecture**: [e.g., AMD64, ARM64]
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, screenshots, error messages, or related
        issues here
      placeholder: Screenshots, error messages, related issues, etc.
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible Solution
      description: |
        If you have ideas on how to fix this, please describe them here
      placeholder: Optional - describe potential solutions...
  - type: dropdown
    id: changelog-category
    attributes:
      label: Changelog Category
      description: |
        Under which CHANGELOG.md section should this fix appear?
      options:
        - Fixed
        - Security
        - Changed
        - No changelog needed
      default: 0
    validations:
      required: true
