---
name: Task
description: Create a new task or work item
title: '[TASK] '
labels: ['task']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Use this template to create a task or work item that needs to be
        completed.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the task
      placeholder: Describe what needs to be done...
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Define what needs to be completed for this task to be considered
        done
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3
    validations:
      required: true
  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any technical notes, considerations, or approach suggestions
      placeholder: Technical details, approach, dependencies, etc.
  - type: textarea
    id: related-issues
    attributes:
      label: Related Issues
      description: Link to any related issues or pull requests
      placeholder: 'Related to #123, Blocks #456, etc.'
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this task
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Additional notes, context, or references...
