# Composite action to set up the CI environment
#
# Installs Node.js and project dependencies by default.
# All inputs default to true — callers typically need zero configuration.
#
# IMPORTANT: The caller must checkout the repository before using this action.
#
# Usage:
#   # Default (Node.js + npm deps)
#   - uses: actions/checkout@v4
#   - uses: ./.github/actions/setup-env

name: 'Setup Environment'
description: 'Set up CI environment with Node.js and project dependencies'

inputs:
  install-node:
    description: 'Install Node.js and run npm ci'
    required: false
    default: 'true'
  node-version:
    description: 'Node.js version (when install-node is true)'
    required: false
    default: '20'

outputs:
  node-version:
    description: 'The Node.js version that was installed'
    value: ${{ steps.setup-node.outputs.node-version }}
  cache-hit:
    description: 'Whether the npm cache was hit'
    value: ${{ steps.setup-node.outputs.cache-hit }}

runs:
  using: composite
  steps:
    # ── Node.js + npm dependencies ───────────────────────────────────────
    - name: Install Node.js
      id: setup-node
      if: inputs.install-node == 'true'
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install npm dependencies
      if: inputs.install-node == 'true'
      shell: bash
      run: npm ci
